spring:
  security:
    oauth2:
      client:
        registration:
          github-client-1:
            client-id: 4ea9ad644a22e7066707
            client-secret: 378a7f78f187326d07f5a8dd0a5beada4e34d7ed
            client-name: Github user
            provider: github
            scope: user
            redirect-uri: http://localhost:8080/login/oauth2/code/github
          github-client-2:
            client-id: 4ea9ad644a22e7066707
            client-secret: 378a7f78f187326d07f5a8dd0a5beada4e34d7ed
            client-name: Github email
            provider: github
            scope: user:email
            redirect-uri: http://localhost:8080/login/oauth2/code/github
          yahoo-oidc:
            client-id: ${YAHOO-CLIENT-ID}
            client-secret: ${YAHOO-CLIENT-SECRET}
          github-repos:
            client-id: 4ea9ad644a22e7066707
            client-secret: 378a7f78f187326d07f5a8dd0a5beada4e34d7ed
            scope: public_repo
            redirect-uri: "{baseUrl}/github-repos"
            provider: github
            client-name: GitHub Repositories
        provider:
          yahoo-oidc:
            issuer-uri: https://api.login.yahoo.com